global:
    scrape_interval: 60s
    evaluation_interval: 60s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "rule.yml"

alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: 'apps'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:21001']
    - job_name: node
      static_configs:
      - targets:
        - node-exporter:9100
